### ISSUE TITLE
Feature: 초기 프로젝트 세팅

### ISSUE THREAD

**Issue by Sonny-Kor** [toduck-App/iOS-to.duck#2]
## Issue

to.duck 초기 프로젝트 세팅

## To-do
- [x] 오픈소스 라이브러리 설치 
  -  [x] Moya(+ Alamofire), Kingfisher, SnapKit, then, OHHTTPSTUB
- [x] gitignore 
- [x] gitattribute 
- [x] codebase 설정
- [x] xcodecloud 를 통한 ci 설정
- [x] 앱 아이콘
